[package]
authors = ["AngelOfSol <julietckilian@gmail.com>"]
edition = "2018"
name = "art-organize"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.0.0-beta.2"
directories = "3.0.1"
lazy_static = "1.4.0"
serde = {version = "1.0.124", features = ["derive"]}
toml = "0.5.8"
winreg = "0.8.0"
