[package]
authors = ["AngelOfSol <julietckilian@gmail.com>"]
edition = "2018"
name = "art-organize"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[workspace]
members = [
  "contextual",
]

[dependencies]
anyhow = "1.0.38"
bincode = "1.3.2"
chrono = "0.4.19"
clap = "3.0.0-beta.2"
contextual = {path = "contextual"}
directories = "3.0.1"
lazy_static = "1.4.0"
serde = {version = "1.0.124", features = ["derive"]}
tokio = {version = "1.3.0", features = ["rt", "rt-multi-thread", "time", "macros", "sync"]}
toml = "0.5.8"
winreg = "0.8.0"
