[package]
authors = ["AngelOfSol <julietckilian@gmail.com>"]
edition = "2018"
name = "search"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
db = {path = "../db"}
nom = "6.1.2"
chrono = "0.4.19"
